/**
 * Canonical-request test vectors.
 *
 * The vectors in test/vectors/canonical.json are COMMITTED so that any
 * refactor of the signing code (or a port to another language) can be checked
 * byte-for-byte. They were generated by scripts/generate-vectors.ts from this
 * repo's own implementation using the FAKE secret below — it is a test
 * fixture, not a real credential.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import {
  buildCanonicalRequest,
  computeHmacSignature,
  sha256HexOfBody,
  signRequest,
  generateNonce,
} from '../src/zennopay/client.js';

interface Vector {
  name: string;
  method: string;
  path: string;
  timestamp: string;
  nonce: string;
  body: string;
  expected: {
    bodyHashHex: string;
    canonical: string;
    signature: string;
  };
}

const FAKE_SECRET = 'test_secret_do_not_use_0123456789abcdef';

const here = path.dirname(fileURLToPath(import.meta.url));
const vectors: Vector[] = JSON.parse(
  fs.readFileSync(path.join(here, 'vectors', 'canonical.json'), 'utf8'),
);

describe('canonical request construction (committed vectors)', () => {
  it('has vectors to test', () => {
    expect(vectors.length).toBeGreaterThanOrEqual(4);
  });

  for (const v of vectors) {
    describe(v.name, () => {
      it('hashes the body correctly', () => {
        expect(sha256HexOfBody(v.body)).toBe(v.expected.bodyHashHex);
      });
      it('builds the canonical string byte-for-byte', () => {
        const canonical = buildCanonicalRequest({
          method: v.method,
          path: v.path,
          timestamp: v.timestamp,
          nonce: v.nonce,
          bodyHashHex: sha256HexOfBody(v.body),
        });
        expect(canonical).toBe(v.expected.canonical);
      });
      it('signs to the expected base64 HMAC', () => {
        const canonical = buildCanonicalRequest({
          method: v.method,
          path: v.path,
          timestamp: v.timestamp,
          nonce: v.nonce,
          bodyHashHex: sha256HexOfBody(v.body),
        });
        expect(computeHmacSignature(FAKE_SECRET, canonical)).toBe(v.expected.signature);
      });
    });
  }
});

describe('canonical rules', () => {
  it('ends with a trailing newline', () => {
    const c = buildCanonicalRequest({
      method: 'POST',
      path: '/v1/payment_intents',
      timestamp: '2026-01-01T00:00:00.000Z',
      nonce: 'a'.repeat(64),
      bodyHashHex: 'abc',
    });
    expect(c.endsWith('abc\n')).toBe(true);
    expect(c.split('\n')).toHaveLength(6); // 5 components + empty string after trailing \n
  });

  it('uppercases the method', () => {
    const c = buildCanonicalRequest({
      method: 'post',
      path: '/x',
      timestamp: 't',
      nonce: 'n',
      bodyHashHex: '',
    });
    expect(c.startsWith('POST\n')).toBe(true);
  });

  it('hashes the empty body to the empty string (NOT sha256 of "")', () => {
    expect(sha256HexOfBody('')).toBe('');
  });

  it('generates 64-hex-char nonces', () => {
    expect(generateNonce()).toMatch(/^[0-9a-f]{64}$/);
  });
});

describe('signRequest', () => {
  it('produces all required headers with a valid signature', () => {
    const body = '{"hello":"world"}';
    const headers = signRequest({
      method: 'POST',
      path: '/v1/payment_intents',
      body,
      keyId: 'test_key_1',
      secret: FAKE_SECRET,
      timestamp: '2026-01-01T00:00:00.000Z',
      nonce: 'f'.repeat(64),
    });
    expect(headers['X-Zennopay-Key-Id']).toBe('test_key_1');
    expect(headers['X-Zennopay-Timestamp']).toBe('2026-01-01T00:00:00.000Z');
    expect(headers['X-Zennopay-Nonce']).toBe('f'.repeat(64));
    const canonical = buildCanonicalRequest({
      method: 'POST',
      path: '/v1/payment_intents',
      timestamp: '2026-01-01T00:00:00.000Z',
      nonce: 'f'.repeat(64),
      bodyHashHex: sha256HexOfBody(body),
    });
    expect(headers['X-Zennopay-Signature']).toBe(computeHmacSignature(FAKE_SECRET, canonical));
  });
});
